### Products
### create products
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "productId": "102",
    "productName": "pocoX8",
    "price": 25000,
    "brand": "poco"
}
### Read all products
GET http://localhost:4000/product-api/products

### Read a product by id
GET http://localhost:4000/product-api/products/101

### update product
PUT http://localhost:4000/product-api/products/101
Content-Type: application/json

{
    "productId": 101,
    "productName": "Laptop",
    "price": 22500,
    "brand": "Dell"
}

### delete product
DELETE http://localhost:4000/product-api/products/102